_core:
  default_config_hash: YPUqVPBFEsvwMa23vT1yY60XrIdvCZdkOZICIV0BtbU
langcode: pt-br
disabled: false
field_template: true
ft_default: default
ft_show_colon: false
ft_layout_builder: true
ft_bc: true
ft_default_bc: false
ft_expert_prefix_suffix_textarea: true
classes:
  region: {  }
  field: {  }
use_field_names: true
exclude_layout_builder_blocks_on_block_field: false
exclude_ds_layout_layout_builder: false
layout_icon_image_bc: true
layout_suggestion_bc: false
